version: '3'

services:
  app:
    image: 'usermanagement'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=vedansh
      - SPRING_DATASOURCE_PASSWORD=vedu0610
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres'
    restart: always
    ports:
       - "5555:5432"
    container_name: db
    environment:
      - POSTGRES_USER=vedansh
      - POSTGRES_PASSWORD=vedu0610
      - POSTGRES_DB=postgres